
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/careerfestival
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create-drop
        default_batch_fetch_size: 1000

  jwt:
    secret: 86221d73fc259a5107f402c07a85d92379a00f9a5add4bd258179733b07de544b8ab747c931715c
    toeknValidTime: ${TOKEN_VALID_TIME}

server:
  port: 9000