name: Dev CI/CD

on:
  push:
    branches:
      - test-cicd
  pull_request:
    types: [closed]
  workflow_dispatch: # (2).수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # (3).OS환경
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'feat-test-cicd') ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/test-cicd')
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4).코드 check out

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # (5).자바 설치
          distribution: 'adopt'

      - name: Grant execute permission for gradlew And Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
        shell: bash # (7).build 시작




      - name: Docker build backend and push to Docker hub
        run: |
          docker login -u euegenechoi -p ${{ secrets.DOCKER_PASSWORD }}
          pwd
          cd backend
          docker build -t careerfestival .
          docker tag careerfestival euegenechoi/careerfestival:latest
          docker push euegenechoi/careerfestival:latest


      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # (8).build 시점의 시간확보

      - name: Show Current Time
        run: echo "CurrentTime=$"
        shell: bash # (9).확보한 시간 보여주기

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
          application_name: careerfestival-dev
          environment_name: Careerfestival-dev-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: docker-compose.yml
          wait_for_deployment: 60

      - name: Docker Compose Up
        run: docker compose up -d